//
//  The MIT License
//
//  Copyright (c) 2014- High-Mobility GmbH (https://high-mobility.com)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//
//
//  UnitPressure+Extensions.swift
//  AutoAPI
//
//  Generated by AutoAPIGenerator for Swift.
//  Copyright © 2021 High-Mobility GmbH. All rights reserved.
//

import Foundation


public extension UnitPressure {

    static let pascals = UnitPressure(symbol: "hm_p", converter: UnitConverterLinear(coefficient: 1.0))
}

extension UnitPressure: AAUnitType {

    public static let measurementID: UInt8 = 0x15

    public static func create(id: UInt8) -> Self? {
        switch id {
        case 0x00:  return UnitPressure.pascals as? Self
        case 0x03:  return UnitPressure.kilopascals as? Self
        case 0x05:  return UnitPressure.inchesOfMercury as? Self
        case 0x06:  return UnitPressure.bars as? Self
        case 0x07:  return UnitPressure.millibars as? Self
        case 0x08:  return UnitPressure.millimetersOfMercury as? Self
        case 0x09:  return UnitPressure.poundsForcePerSquareInch as? Self

        default:    return nil
        }
    }


    public var identifiers: [UInt8]? {
        switch self {
        case .pascals: return [Self.measurementID, 0x00]
        case .kilopascals: return [Self.measurementID, 0x03]
        case .inchesOfMercury: return [Self.measurementID, 0x05]
        case .bars: return [Self.measurementID, 0x06]
        case .millibars: return [Self.measurementID, 0x07]
        case .millimetersOfMercury: return [Self.measurementID, 0x08]
        case .poundsForcePerSquareInch: return [Self.measurementID, 0x09]

        default: return nil
        }
    }

    public var name: String? {
        switch self {
        case .pascals: return "pascals"
        case .kilopascals: return "kilopascals"
        case .inchesOfMercury: return "inchesOfMercury"
        case .bars: return "bars"
        case .millibars: return "millibars"
        case .millimetersOfMercury: return "millimetersOfMercury"
        case .poundsForcePerSquareInch: return "poundsForcePerSquareInch"

        default: return nil
        }
    }
}
