import Foundation
import HMUtilities

extension AAAutoAPI {
    static let capabilities: [AACapability.Type] = [
        AAAdas.self,
        AABrowser.self,
        AACapabilities.self,
        AACharging.self,
        AAChargingSession.self,
        AAChassisSettings.self,
        AAClimate.self,
        AACrash.self,
        AACruiseControl.self,
        AADashboardLights.self,
        AADiagnostics.self,
        AADoors.self,
        AADriverFatigue.self,
        AAEngine.self,
        AAFailureMessage.self,
        AAFirmwareVersion.self,
        AAFueling.self,
        AAGraphics.self,
        AAHeartRate.self,
        AAHistorical.self,
        AAHomeCharger.self,
        AAHonkHornFlashLights.self,
        AAHood.self,
        AAIgnition.self,
        AAKeyfobPosition.self,
        AALightConditions.self,
        AALights.self,
        AAMaintenance.self,
        AAMessaging.self,
        AAMobile.self,
        AAMultiCommand.self,
        AANaviDestination.self,
        AANotifications.self,
        AAOffroad.self,
        AAParkingBrake.self,
        AAParkingTicket.self,
        AAPowerTakeoff.self,
        AARace.self,
        AARemoteControl.self,
        AARooftopControl.self,
        AASeats.self,
        AATachograph.self,
        AATextInput.self,
        AATheftAlarm.self,
        AATrips.self,
        AATrunk.self,
        AAUniversal.self,
        AAUsage.self,
        AAValetMode.self,
        AAVehicleInformation.self,
        AAVehicleLocation.self,
        AAVehicleStatus.self,
        AAVehicleTime.self,
        AAVideoHandover.self,
        AAWakeUp.self,
        AAWeatherConditions.self,
        AAWiFi.self,
        AAWindows.self,
        AAWindscreen.self
    ]

    static let protocolVersion: UInt8 = 0x0d
}
