//
//  The MIT License
//
//  Copyright (c) 2014- High-Mobility GmbH (https://high-mobility.com)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//
//
//  AAFuelingTests.swift
//  AutoAPI
//
//  Generated by AutoAPIGenerator for Swift.
//  Copyright © 2021 High-Mobility GmbH. All rights reserved.
//

import Foundation
import HMUtilities
import XCTest
@testable import AutoAPI


final class AAFuelingTests: XCTestCase {

    // MARK: State Properties
    
    func testGasFlapLock() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x01, 0x02, 0x00, 0x04, 0x01, 0x00, 0x01, 0x01]
        
        guard let capability = try? AAAutoAPI.parseBytes(bytes) as? AAFueling else {
            return XCTFail("Could not parse bytes as `AAFueling`")
        }
        
        XCTAssertEqual(capability.gasFlapLock?.value, AALockState.locked)
    }
    
    func testGasFlapPosition() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x01, 0x03, 0x00, 0x04, 0x01, 0x00, 0x01, 0x00]
        
        guard let capability = try? AAAutoAPI.parseBytes(bytes) as? AAFueling else {
            return XCTFail("Could not parse bytes as `AAFueling`")
        }
        
        XCTAssertEqual(capability.gasFlapPosition?.value, AAPosition.closed)
    }


    // MARK: Getters
    
    func testGetGasFlapState() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x00]
        
        XCTAssertEqual(bytes, AAFueling.getGasFlapState())
    }
    
    func testGetGasFlapStateAvailability() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x02]
        
        XCTAssertEqual(bytes, AAFueling.getGasFlapStateAvailability())
    }
    
    func testGetGasFlapStateProperties() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x00, 0x02]
        let getterBytes = AAFueling.getGasFlapStateProperties(ids: .gasFlapLock)
        
        XCTAssertEqual(bytes, getterBytes)
    }
    
    func testGetGasFlapStatePropertiesAvailability() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x02, 0x02]
        let getterBytes = AAFueling.getGasFlapStatePropertiesAvailability(ids: .gasFlapLock)
        
        XCTAssertEqual(bytes, getterBytes)
    }


    // MARK: Setters
    
    func testControlGasFlap() {
        let bytes: [UInt8] = [0x0c, 0x00, 0x40, 0x01, 0x02, 0x00, 0x04, 0x01, 0x00, 0x01, 0x01, 0x03, 0x00, 0x04, 0x01, 0x00, 0x01, 0x00]
        let setterBytes = AAFueling.controlGasFlap(gasFlapLock: AALockState.locked, gasFlapPosition: AAPosition.closed)
        
        XCTAssertEqual(bytes, setterBytes)
    }


    // MARK: Identifiers
    
    func testCapabilityIdentifier() {
        XCTAssertEqual(AAFueling.identifier, 0x0040)
    }
    
    func testPropeertyIdentifiers() {
        XCTAssertEqual(AAFueling.PropertyIdentifier.gasFlapLock.rawValue, 0x02)
        XCTAssertEqual(AAFueling.PropertyIdentifier.gasFlapPosition.rawValue, 0x03)
    }
}
