//
//  The MIT License
//
//  Copyright (c) 2014- High-Mobility GmbH (https://high-mobility.com)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//
//
//  AAHeartRateTests.swift
//  AutoAPI
//
//  Generated by AutoAPIGenerator for Swift.
//  Copyright © 2021 High-Mobility GmbH. All rights reserved.
//

import Foundation
import HMUtilities
import XCTest
@testable import AutoAPI


final class AAHeartRateTests: XCTestCase {

    // MARK: Non-state or Deprecated Properties
    
    func testHeartRate() {
        let bytes: [UInt8] = [0x01, 0x00, 0x0d, 0x01, 0x00, 0x0a, 0x0e, 0x08, 0x40, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        
        guard let property: AAProperty<Measurement<UnitFrequency>> = AAOpaqueProperty(bytes: bytes)?.property() else {
            return XCTFail("Could not create a property for `.heartRate`")
        }
        
        XCTAssertEqual(property.value, Measurement<UnitFrequency>(value: 64.0, unit: .timesPerMinute))
    }


    // MARK: Setters
    
    func testSendHeartRate() {
        let bytes: [UInt8] = [0x0d, 0x00, 0x29, 0x01, 0x01, 0x00, 0x0d, 0x01, 0x00, 0x0a, 0x0e, 0x08, 0x40, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        let setterBytes = AAHeartRate.sendHeartRate(heartRate: Measurement<UnitFrequency>(value: 64.0, unit: .timesPerMinute))
        
        XCTAssertEqual(bytes, setterBytes)
    }


    // MARK: Identifiers
    
    func testCapabilityIdentifier() {
        XCTAssertEqual(AAHeartRate.identifier, 0x0029)
    }
    
    func testPropeertyIdentifiers() {
        XCTAssertEqual(AAHeartRate.PropertyIdentifier.heartRate.rawValue, 0x01)
    }
}
