//
//  The MIT License
//
//  Copyright (c) 2014- High-Mobility GmbH (https://high-mobility.com)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//
//
//  AAChargingLocation.swift
//  AutoAPI
//
//  Generated by AutoAPIGenerator for Swift.
//  Copyright © 2021 High-Mobility GmbH. All rights reserved.
//

import Foundation
import HMUtilities


public final class AAChargingLocation: Codable, HMBytesConvertable {

    /// Municipality component of the address.
    public var municipality: String

    /// Full formatted address.
    public var formattedAddress: String

    /// Street address component.
    public var streetAddress: String


    /// Initialise `AAChargingLocation` with arguments.
    ///
    /// - parameters:
    ///     - municipality: Municipality component of the address.
    ///     - formattedAddress: Full formatted address.
    ///     - streetAddress: Street address component.
    public init(municipality: String, formattedAddress: String, streetAddress: String) {
        self.bytes = [municipality.bytes.sizeBytes(amount: 2), municipality.bytes, formattedAddress.bytes.sizeBytes(amount: 2), formattedAddress.bytes, streetAddress.bytes.sizeBytes(amount: 2), streetAddress.bytes].flatMap { $0 }
        self.municipality = municipality
        self.formattedAddress = formattedAddress
        self.streetAddress = streetAddress
    }


    // MARK: HMBytesConvertable
    
    public let bytes: [UInt8]
    
    
    /// Initialise `AAChargingLocation` with bytes.
    ///
    /// - parameters:
    ///     - bytes: Bytes array in `[UInt8]`.
    public required init?(bytes: [UInt8]) {
        guard bytes.count >= 0 else {
            return nil
        }
    
        guard let municipality = bytes.extract(stringFrom: 0),
    		  let formattedAddress = bytes.extract(stringFrom: (2 + municipality.bytes.count)),
    		  let streetAddress = bytes.extract(stringFrom: (4 + municipality.bytes.count + formattedAddress.bytes.count)) else {
            return nil
        }
    
        self.bytes = bytes
        self.municipality = municipality
        self.formattedAddress = formattedAddress
        self.streetAddress = streetAddress
    }
}
