//
//  The MIT License
//
//  Copyright (c) 2014- High-Mobility GmbH (https://high-mobility.com)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//
//
//  AAChargingCost.swift
//  AutoAPI
//
//  Generated by AutoAPIGenerator for Swift.
//  Copyright © 2021 High-Mobility GmbH. All rights reserved.
//

import Foundation
import HMUtilities


public final class AAChargingCost: Codable, HMBytesConvertable {

    /// Currency ISO code.
    public var currency: String

    /// Calculated charging cost.
    public var calculatedChargingCost: Float

    /// Calculated savings from charging.
    public var calculatedSavings: Float

    /// Simulated charging costs.
    public var simulatedImmediateChargingCost: Float


    /// Initialise `AAChargingCost` with arguments.
    ///
    /// - parameters:
    ///     - currency: Currency ISO code.
    ///     - calculatedChargingCost: Calculated charging cost.
    ///     - calculatedSavings: Calculated savings from charging.
    ///     - simulatedImmediateChargingCost: Simulated charging costs.
    public init(currency: String, calculatedChargingCost: Float, calculatedSavings: Float, simulatedImmediateChargingCost: Float) {
        self.bytes = [currency.bytes.sizeBytes(amount: 2), currency.bytes, calculatedChargingCost.bytes, calculatedSavings.bytes, simulatedImmediateChargingCost.bytes].flatMap { $0 }
        self.currency = currency
        self.calculatedChargingCost = calculatedChargingCost
        self.calculatedSavings = calculatedSavings
        self.simulatedImmediateChargingCost = simulatedImmediateChargingCost
    }


    // MARK: HMBytesConvertable
    
    public let bytes: [UInt8]
    
    
    /// Initialise `AAChargingCost` with bytes.
    ///
    /// - parameters:
    ///     - bytes: Bytes array in `[UInt8]`.
    public required init?(bytes: [UInt8]) {
        guard bytes.count >= 12 else {
            return nil
        }
    
        guard let currency = bytes.extract(stringFrom: 0),
    		  let calculatedChargingCost = Float(bytes: bytes[(2 + currency.bytes.count)..<(6 + currency.bytes.count)].bytes),
    		  let calculatedSavings = Float(bytes: bytes[(6 + currency.bytes.count)..<(10 + currency.bytes.count)].bytes),
    		  let simulatedImmediateChargingCost = Float(bytes: bytes[(10 + currency.bytes.count)..<(14 + currency.bytes.count)].bytes) else {
            return nil
        }
    
        self.bytes = bytes
        self.currency = currency
        self.calculatedChargingCost = calculatedChargingCost
        self.calculatedSavings = calculatedSavings
        self.simulatedImmediateChargingCost = simulatedImmediateChargingCost
    }
}
